---
  # file: roles/common/tasks/main.yml

- name: make sure deadsnakes repository is added
  apt_repository:
    repo: 'ppa:fkrull/deadsnakes'

- name: make sure aptitude has updated
  apt:
    update_cache: yes

- name: make sure latest python is installed
  apt:
    name: "{{python_executable}}"
    state: installed

- name: Check to see if pip is already installed.
  command: "pip --version"
  ignore_errors: true
  changed_when: false # read-only task
  check_mode: no
  register: pip_is_installed

- name: Download pip.
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp
  when: pip_is_installed.rc != 0

- name: Install pip.
  command: "{{python_executable}} /tmp/get-pip.py"
  become: yes
  when: pip_is_installed.rc != 0

- name: Delete get-pip.py.
  file: state=absent path=/tmp/get-pip.py
  when: pip_is_installed.rc != 0
