# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
