# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170317_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
